#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import os
import subprocess
import tempfile
import textwrap

from bs4 import BeautifulSoup

working_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(working_dir)


tmp_dir = tempfile.mkdtemp()

subprocess.check_call(['sphinx-build', '-b', 'html', '.', tmp_dir])

html_doc = open(os.path.join(tmp_dir, 'api_src.html')).read()
soup = BeautifulSoup(html_doc, 'html.parser')

with open('api.rst', 'w') as f:
    f.write('.. This file is autogenerated; edits will be lost.\n')
    f.write('   To rebuild this file, run "tox -e build_api_ref".\n\n')

    f.write('API reference\n')
    f.write('=============\n\n')

    reference = soup.find('div', attrs={'id': 'api-reference'})
    for section in reference.findAll('div', attrs={'class': 'section'}):
        title = section.find('h2')
        title.extract()
        f.write(title.contents[0] + '\n')
        f.write('*' * len(title.contents[0]) + '\n\n')

        f.write('.. raw:: html\n\n')

        f.write(textwrap.indent(
            text=''.join([str(s) for s in section.contents]).strip(),
            prefix=' ' * 4
        ))

        id_span = section.find('span')
        id_span.extract()

        f.write('\n\n')
